// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnHZuvdDdJmJu4HsYK8MofK_Bl_yViays',
    appId: '1:462385155135:web:0d5056ea6a63f552f23c8a',
    messagingSenderId: '462385155135',
    projectId: 'uas-pmob-7966b',
    authDomain: 'uas-pmob-7966b.firebaseapp.com',
    storageBucket: 'uas-pmob-7966b.appspot.com',
    measurementId: 'G-74313HB1QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDngnG3BRnUK7vUHu0HU8GNw1w__oHwWgU',
    appId: '1:462385155135:android:6f7b268a8eda72cff23c8a',
    messagingSenderId: '462385155135',
    projectId: 'uas-pmob-7966b',
    storageBucket: 'uas-pmob-7966b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE6Qr57pgZ0APvTbmAvUvJ2XTHHh7drUk',
    appId: '1:462385155135:ios:c5ff1456fa19e867f23c8a',
    messagingSenderId: '462385155135',
    projectId: 'uas-pmob-7966b',
    storageBucket: 'uas-pmob-7966b.appspot.com',
    iosBundleId: 'com.example.kelilingPontianak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE6Qr57pgZ0APvTbmAvUvJ2XTHHh7drUk',
    appId: '1:462385155135:ios:c5ff1456fa19e867f23c8a',
    messagingSenderId: '462385155135',
    projectId: 'uas-pmob-7966b',
    storageBucket: 'uas-pmob-7966b.appspot.com',
    iosBundleId: 'com.example.kelilingPontianak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnHZuvdDdJmJu4HsYK8MofK_Bl_yViays',
    appId: '1:462385155135:web:f7b7a1add08ae308f23c8a',
    messagingSenderId: '462385155135',
    projectId: 'uas-pmob-7966b',
    authDomain: 'uas-pmob-7966b.firebaseapp.com',
    storageBucket: 'uas-pmob-7966b.appspot.com',
    measurementId: 'G-9WYF2678FH',
  );
}
